services:
  - type: web
    name: rishikrit
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn rishikrit.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,rishikrit.onrender.com"
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
